name: task
description: "Developer task"


publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ^3.5.3


dependencies:
  flutter:
    sdk: flutter



  cupertino_icons: ^1.0.8
  dio: ^5.7.0
  flutter_screenutil: ^5.9.3
  flutter_bloc: ^8.1.6
  flutter_svg: ^2.0.10+1
  equatable: ^2.0.5
  get_it: ^8.0.0
  pretty_dio_logger: ^1.4.0
  shimmer: ^3.0.0
  lottie: ^3.1.2


dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^4.0.0



flutter:


  uses-material-design: true


  assets:
    - assets/icons/
    - assets/animations/
    - assets/fonts/Poppins/
    - assets/fonts/
    - assets/images/


  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins/Poppins-Black.ttf
          weight: 900
        - asset: assets/fonts/Poppins/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins/Poppins-Regular.ttf
          weight: 400